export const PATH = {
  PROFILELADMIN: "/profileladmin",
  ADMINNAVBAR: "/adminnavbar",
  GYMSTATS: "/gymstats",
  MEMBERS: "/members",
  MEMBERTABLE: "/membertable",
  PAYMENT: "/payment",
  SERVICEFORM: "/serviceform",
  SERVICES: "/services",
  SIDEBAR: "/sidebar",
  TABLEADMIN: "/tableadmin",
  USERLIST: "/userlist",
  PRODUCTLIST: "/product",
  HOME: "/home",
  ATTENDANCE: "/attandance",
  ATTENDANCEDATA: "/attendancedata",
};
